env:
  num_envs: 4096
  num_dof: 12
  num_actions: 12
  env_spacing: 3.0
  send_timeouts: true
  episode_length_s: 20
  num_observation_history: 10
  sparse_obs_history: null
  num_estimator_obs_history: null
  sparse_estimator_obs_history: null
  dof_history_length: 2
  dof_history_step_skip: 0
  action_history_length: 2
  action_history_step_skip: 0
  policy_observation_components:
    - [commands, 3, true]
    - [global_linear_vel, 3, false]
    - [linear_vel, 3, false]
    - [angular_vel, 3, false]
    - [projected_gravity, 3, true]
    - [dof_positions, 12, true]
    - [dof_velocities, 12, true]
    - [dof_position_history, 24, false]
    - [dof_velocity_history, 24, false]
    - [last_actions, 12, true]
    - [action_history, 24, false]
    - [timing_parameter, 1, false]
    - [clock_inputs, 4, false]
    - [yaw, 1, false]
    - [contact_states, 4, false]
    - [height_measurements, 77, true]
  estimator_observation_components:
    - [commands, null, false]
    - [global_linear_vel, 3, false]
    - [linear_vel, 3, false]
    - [angular_vel, 3, false]
    - [projected_gravity, 3, true]
    - [dof_positions, 12, true]
    - [dof_velocities, 12, true]
    - [dof_position_history, 24, false]
    - [dof_velocity_history, 24, false]
    - [last_actions, 12, true]
    - [action_history, 24, false]
    - [timing_parameter, 1, false]
    - [clock_inputs, 4, false]
    - [yaw, 1, false]
    - [contact_states, 4, false]
    - [height_measurements, 77, true]
  privileged_observation_components:
    - [friction, 1, true]
    - [ground_friction, null, false]
    - [restitution, 1, true]
    - [base_mass, 1, false]
    - ['com_displacement ', 3, false]
    - [motor_strength, 12, false]
    - [motor_offset, 12, false]
    - [body_height, 1, false]
    - [body_velocity, 3, true]
    - [body_angular_velocity, 3, false]
    - [gravity, 3, false]
    - [clock_inputs, 4, false]
    - [desired_contact_states, 4, false]
    - [contact_states, 4, true]
    - [feet_height, 4, false]
    - [height_measurements_bias, 3, false]
    - [height_measurements_z_bias, 1, true]
  compute_true_feet_height: false
  record_video: true
  recording_width_px: 368
  recording_height_px: 240
  recording_mode: COLOR
  num_recording_envs: 1
  debug_viz: false
  all_agents_share: false
  max_episode_length: defined_at_runtime
  num_height_points: 77
terrain:
  mesh_type: trimesh
  horizontal_scale: 0.1
  vertical_scale: 0.005
  border_size: 10.0
  curriculum: false
  legacy_curriculum: true
  static_friction: 1.0
  dynamic_friction: 1.0
  restitution: 0.0
  terrain_noise_magnitude: 0.05
  terrain_smoothness: 0.005
  selected: false
  terrain_kwargs: null
  min_init_terrain_level: 0
  max_init_terrain_level: 5
  terrain_length: 5.0
  terrain_width: 5.0
  num_rows: 20
  num_cols: 10
  terrain_proportions: [0, 0, 0, 0, 1.0, 0, 0, 0.0, 0.0]
  slope_treshold: 0.25
  difficulty_scale: 1.0
  x_init_range: 0.2
  y_init_range: 0.2
  yaw_init_range: 3.14
  x_init_offset: 0.0
  y_init_offset: 0.0
  teleport_robots: false
  teleport_thresh: 0.3
  max_platform_height: 0.15
  center_robots: true
  center_span: 5
  measure_heights: true
  measured_points_x: [-0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  measured_points_y: [-0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3]
  height_measurements_per_step_xy_noise_std: 0.05
  height_measurements_per_step_z_noise_std: 0.025
  height_measurements_per_env_xy_noise_std: 0.05
  height_measurements_per_env_z_noise_std: 0.05
  height_measurements_per_env_noise_prob: 0.2
  height_measurements_per_env_resampling_s: 7
  proportions: [defined_at_runtime, defined_at_runtime, defined_at_runtime, defined_at_runtime,
    defined_at_runtime, defined_at_runtime, defined_at_runtime, defined_at_runtime,
    defined_at_runtime]
  num_sub_terrains: 200
  width_per_env_pixels: 50
  length_per_env_pixels: 50
  border: 100
  tot_cols: 700
  tot_rows: 1200
  x_offset: 0
  rows_offset: 0
  env_length: 5.0
  env_width: 5.0
  max_terrain_level: 20
commands:
  command_curriculum: true
  max_reverse_curriculum: 1.0
  max_forward_curriculum: 1.0
  yaw_command_curriculum: false
  max_yaw_curriculum: 1.0
  exclusive_command_sampling: false
  num_commands: 3
  resampling_time: 10
  subsample_gait: false
  gait_interval_s: 10.0
  vel_interval_s: 10.0
  jump_interval_s: 20.0
  jump_duration_s: 0.1
  jump_height: 0.3
  heading_command: false
  global_reference: false
  observe_accel: false
  distributional_commands: false
  curriculum_type: RewardThresholdCurriculum
  lipschitz_threshold: 0.9
  num_lin_vel_bins: 30
  lin_vel_step: 0.3
  num_ang_vel_bins: 30
  ang_vel_step: 0.3
  distribution_update_extension_distance: 1
  curriculum_seed: 100
  lin_vel_x: [-0.5, 0.5]
  lin_vel_y: [-0.5, 0.5]
  ang_vel_yaw: [-1.0, 1.0]
  body_height_cmd: [0.0, 0.0]
  impulse_height_commands: false
  limit_vel_x: [-1.0, 1.5]
  limit_vel_y: [-1.0, 1.0]
  limit_vel_yaw: [-1.5, 1.5]
  limit_body_height: [0.0, 0.0]
  limit_gait_phase: [0.0, 0.0]
  limit_gait_offset: [0.0, 0.0]
  limit_gait_bound: [0.0, 0.0]
  limit_gait_frequency: [0.0, 0.0]
  limit_gait_duration: [0.0, 0.0]
  limit_footswing_height: [0.0, 0.0]
  limit_body_pitch: [0.0, 0.0]
  limit_body_roll: [0.0, 0.0]
  limit_aux_reward_coef: [0.0, 0.0]
  limit_compliance: [0.0, 0.01]
  limit_stance_width: [0.0, 0.0]
  limit_stance_length: [0.0, 0.0]
  num_bins_vel_x: 10
  num_bins_vel_y: 10
  num_bins_vel_yaw: 10
  num_bins_body_height: 1
  num_bins_gait_frequency: 1
  num_bins_gait_phase: 1
  num_bins_gait_offset: 1
  num_bins_gait_bound: 1
  num_bins_gait_duration: 3
  num_bins_footswing_height: 1
  num_bins_body_pitch: 1
  num_bins_body_roll: 1
  num_bins_aux_reward_coef: 1
  num_bins_compliance: 1
  num_bins_stance_width: 1
  num_bins_stance_length: 1
  heading_range: [-3.14, 3.14]
  gait_phase_cmd_range: [0.0, 0.0]
  gait_offset_cmd_range: [0.0, 0.0]
  gait_bound_cmd_range: [0.0, 0.0]
  gait_frequency_cmd_range: [0.0, 0.0]
  gait_duration_cmd_range: [0.0, 0.0]
  footswing_height_range: [0.0, 0.0]
  body_pitch_range: [0.0, 0.0]
  body_roll_range: [0.0, 0.0]
  aux_reward_coef_range: [0.0, 0.0]
  stance_width_range: [0.0, 0.0]
  stance_length_range: [0.0, 0.0]
  exclusive_phase_offset: true
  binary_phases: false
  pacing_offset: false
  balance_gait_distribution: true
  gaitwise_curricula: true
  train_standing_still: true
  standing_still_prob: 0.05
  standing_still_explicit_flag: false
  heading: [-3.14, 3.14]
curriculum_thresholds:
  tracking_lin_vel: 0.8
  tracking_ang_vel: 0.5
  tracking_contacts_shaped_force: 0.8
  tracking_contacts_shaped_vel: 0.8
init_state:
  pos: [0.0, 0.0, 0.34]
  rot: [0.0, 0.0, 0.0, 1.0]
  lin_vel: [0.0, 0.0, 0.0]
  ang_vel: [0.0, 0.0, 0.0]
  default_joint_angles:
    FL_hip_joint: 0.1
    RL_hip_joint: 0.1
    FR_hip_joint: -0.1
    RR_hip_joint: -0.1
    FL_thigh_joint: 0.8
    RL_thigh_joint: 0.8
    FR_thigh_joint: 0.8
    RR_thigh_joint: 0.8
    FL_calf_joint: -1.5
    RL_calf_joint: -1.5
    FR_calf_joint: -1.5
    RR_calf_joint: -1.5
control:
  control_type: P
  stiffness:
    joint: 25.0
  damping:
    joint: 0.5
  action_scale: 0.25
  hip_scale_reduction: 1.0
  decimation: 4
asset:
  file: '{MINI_GYM_ROOT_DIR}/resources/robots/go1_backpack_v3/urdf/go1_backpack.urdf'
  foot_name: foot
  penalize_contacts_on: [thigh, calf]
  terminate_after_contacts_on: [base]
  disable_gravity: false
  collapse_fixed_joints: true
  fix_base_link: false
  default_dof_drive_mode: 3
  self_collisions: 1
  replace_cylinder_with_capsule: true
  flip_visual_attachments: false
  density: 0.001
  angular_damping: 0.0
  linear_damping: 0.0
  max_angular_velocity: 1000.0
  max_linear_velocity: 1000.0
  armature: 0.0
  thickness: 0.01
domain_rand:
  rand_interval_s: 4
  randomize_rigids_after_start: true
  randomize_friction: true
  friction_range: [0.0, 4.0]
  randomize_restitution: true
  restitution_range: [0.0, 0.4]
  randomize_base_mass: true
  added_mass_range: [-2.0, 2.0]
  randomize_com_displacement: false
  com_displacement_range: [-0.15, 0.15]
  randomize_motor_strength: true
  motor_strength_range: [0.9, 1.1]
  randomize_Kp_factor: false
  Kp_factor_range: [0.8, 1.3]
  randomize_Kd_factor: false
  Kd_factor_range: [0.5, 1.5]
  gravity_rand_interval_s: 8.0
  gravity_impulse_duration: 0.99
  randomize_gravity: true
  gravity_range: [-1.0, 1.0]
  push_robots: true
  push_interval_s: 15.0
  max_push_vel_xy: 1.0
  randomize_lag_timesteps: true
  lag_timesteps: 6
  restitution: 0.5
  randomize_ground_friction: false
  ground_friction_range: [0.0, 0.0]
  randomize_motor_offset: true
  motor_offset_range: [-0.02, 0.02]
  randomize_friction_indep: false
  push_interval: defined_at_runtime
  rand_interval: defined_at_runtime
  gravity_rand_interval: defined_at_runtime
  gravity_rand_duration: defined_at_runtime
rewards:
  reward_curriculum_factor_init: 0.001
  reward_curriculum_factor_rate: 0.99
  only_positive_rewards: false
  only_positive_rewards_ji22_style: false
  total_reward_function: leaky_relu_0.25
  sigma_rew_neg: 5
  reward_container_name: CoRLRewards
  tracking_sigma: 0.25
  tracking_sigma_lat: 0.25
  tracking_sigma_long: 0.25
  tracking_sigma_yaw: 0.25
  soft_dof_pos_limit: 0.9
  soft_dof_vel_limit: 1.0
  soft_torque_limit: 0.7
  base_height_target: 0.3
  feet_air_time_rsl_period: 0.25
  feet_air_time_rsl_curriculum: true
  feet_air_time_period: 0.25
  feet_air_time_max: 0.25
  max_contact_force: 100.0
  use_terminal_body_impact: true
  use_terminal_body_height: false
  terminal_body_height: 0.1
  use_terminal_foot_height: false
  terminal_foot_height: -0.005
  use_terminal_roll_pitch: true
  terminal_body_ori: 1.39626
  kappa_gait_probs: 0.07
  gait_force_sigma: 100.0
  gait_vel_sigma: 10.0
  footswing_height: 0.09
  hip_weight: 3
  thigh_weight: 1
  calf_weight: 1
  contact_condition_scale: -1
  use_adaptive_period: false
  use_adaptive_stancemode: 0
  start_tracking_sigma: 1
  end_sigma_curriculum_iter: 0
  start_tracking_sigma_yaw: 0.66
  end_sigma_yaw_curriculum_iter: 0
  stancemode_multiplier: 10
  dof_pos_hip_weight: 3.0
  dof_pos_thigh_weight: 1.0
  dof_pos_calf_weight: 0.0
  torque_hip_weight: 1.0
  torque_thigh_weight: 1.0
  torque_calf_weight: 1.0
  torque_pos_thigh_weight: 1.0
  torque_pos_calf_weight: 1.0
reward_scales:
  termination: 0
  tracking_lin_vel: 1.0
  tracking_ang_vel: 0.5
  lin_vel_z: -2.0
  ang_vel_xy: -0.05
  orientation: -2.0
  torques: -0.0002
  dof_vel: 0
  dof_acc: -2.5e-07
  base_height: -5
  feet_air_time: 0.0
  feet_air_time_rsl: 3.0
  collision: -1.0
  feet_stumble: -0.0
  action_rate: -0.01
  stand_still: -0.0
  tracking_lin_vel_lat: 0.0
  tracking_lin_vel_long: 0.0
  tracking_contacts: 0.0
  tracking_contacts_shaped: 0.0
  tracking_contacts_shaped_force: 0.0
  tracking_contacts_shaped_vel: 0
  jump: 0.0
  energy: 0.0
  energy_expenditure: 0.0
  survival: 0.0
  dof_pos_limits: -10.0
  feet_contact_forces: 0.0
  feet_slip: -0.05
  feet_clearance_cmd_linear: -0.0
  thigh_angle: 0.0
  dof_pos: -0.1
  action_smoothness_1: 0
  action_smoothness_2: 0
  base_motion: 0.0
  feet_impact_vel: -0.0
  raibert_heuristic: -0.0
  dof_pos_stancemode: 0.0
  torque_limits: -10.0
normalization:
  clip_observations: 100.0
  clip_actions: 20.0
  friction_range: [-0.5, 6.0]
  ground_friction_range: [0.05, 4.5]
  restitution_range: [0, 0.4]
  added_mass_range: [-1.0, 3.0]
  com_displacement_range: [-0.1, 0.1]
  motor_strength_range: [0.9, 1.1]
  motor_offset_range: [-0.05, 0.05]
  Kp_factor_range: [0.8, 1.3]
  Kd_factor_range: [0.5, 1.5]
  joint_friction_range: [0.0, 0.7]
  contact_force_range: [0.0, 50.0]
  contact_state_range: [0.0, 1.0]
  body_velocity_range: [-6.0, 6.0]
  x_velocity_range: [-2, 2]
  y_velocity_range: [-1, 1]
  z_velocity_range: [-1, 1]
  pitch_velocity_range: [-2.0, 2.0]
  roll_velocity_range: [-2.0, 2.0]
  yaw_velocity_range: [-2.0, 2.0]
  foot_height_range: [0.02, 0.08]
  body_height_range: [0.0, 0.6]
  gravity_range: [-1.0, 1.0]
  motion: [-0.01, 0.01]
  height_measurements_bias_range: [-0.1, 0.1]
  height_measurements_z_bias_range: [-0.05, 0.05]
obs_scales:
  linear_vel: 2.0
  angular_vel: 0.25
  projected_gravity: 1.0
  dof_positions: 1.0
  dof_velocities: 0.05
  height_measurements: 5.0
  body_height_cmd: 2.0
  gait_phase_cmd: 1.0
  gait_freq_cmd: 1.0
  footswing_height_cmd: 0.15
  body_pitch_cmd: 0.3
  body_roll_cmd: 0.3
  aux_reward_cmd: 1.0
  compliance_cmd: 1.0
  stance_width_cmd: 1.0
  stance_length_cmd: 1.0
obs_bias:
  height_measurements: 0.3
noise:
  add_noise: true
  noise_level: 1.0
noise_scales:
  contact_states: 0.05
  height_measurements: 0
  commands: 0
  global_linear_vel: 0.1
  linear_vel: 0.1
  angular_vel: 0.2
  projected_gravity: 0.05
  dof_positions: 0.01
  dof_velocities: 1.5
  dof_position_history: 0.01
  dof_velocity_history: 1.5
  last_actions: 0
  action_history: 0
  timing_parameter: 0
  clock_inputs: 0
  yaw: 0
viewer:
  ref_env: 0
  pos: [10, 0, 6]
  lookat: [11.0, 5, 3.0]
sim:
  dt: 0.005
  substeps: 1
  gravity: [0.0, 0.0, -9.81]
  up_axis: 1
  use_gpu_pipeline: true
  physx:
    num_threads: 10
    solver_type: 1
    num_position_iterations: 4
    num_velocity_iterations: 0
    contact_offset: 0.01
    rest_offset: 0.0
    bounce_threshold_velocity: 0.5
    max_depenetration_velocity: 1.0
    max_gpu_contact_pairs: 8388608
    default_buffer_size_multiplier: 5
    contact_collection: 2
cfg_ppo:
  seed: 1
  runner_class_name: OnPolicyRunner
  policy:
    init_noise_std: 1.0
    actor_hidden_dims: [512, 256, 128]
    critic_hidden_dims: [512, 256, 128]
    activation: elu
    adaptation_module_branch_hidden_dims: [256, 128]
    use_decoder: false
  algorithm:
    value_loss_coef: 1.0
    use_clipped_value_loss: true
    clip_param: 0.2
    entropy_coef: 0.01
    num_learning_epochs: 5
    num_mini_batches: 4
    learning_rate: 0.001
    adaptation_module_learning_rate: 0.001
    num_adaptation_module_substeps: 1
    schedule: adaptive
    lr_adaptive_schedule_decay: 1.25
    gamma: 0.99
    lam: 0.95
    desired_kl: 0.01
    max_grad_norm: 1.0
    selective_adaptation_module_loss: false
  runner:
    algorithm_class_name: RMA
    num_steps_per_env: 24
    max_iterations: 1500
    save_interval: 500
    save_video_interval: 250
    save_curriculum_plot_interval: 10
    log_freq: 10
    resume: false
    load_run: -1
    checkpoint: -1
    resume_path: null
    resume_curriculum: true
    wandb_logging: true
    wandb_project: robodog-exteroceptive-controller
    wandb_entity: pbl-robodog-rl
    wandb_note: Extero, full hist 10
command_ranges:
  command_curriculum: true
  max_reverse_curriculum: 1.0
  max_forward_curriculum: 1.0
  yaw_command_curriculum: false
  max_yaw_curriculum: 1.0
  exclusive_command_sampling: false
  num_commands: 3
  resampling_time: 10
  subsample_gait: false
  gait_interval_s: 10.0
  vel_interval_s: 10.0
  jump_interval_s: 20.0
  jump_duration_s: 0.1
  jump_height: 0.3
  heading_command: false
  global_reference: false
  observe_accel: false
  distributional_commands: false
  curriculum_type: RewardThresholdCurriculum
  lipschitz_threshold: 0.9
  num_lin_vel_bins: 30
  lin_vel_step: 0.3
  num_ang_vel_bins: 30
  ang_vel_step: 0.3
  distribution_update_extension_distance: 1
  curriculum_seed: 100
  lin_vel_x: [-0.5, 0.5]
  lin_vel_y: [-0.5, 0.5]
  ang_vel_yaw: [-1.0, 1.0]
  body_height_cmd: [0.0, 0.0]
  impulse_height_commands: false
  limit_vel_x: [-1.0, 1.5]
  limit_vel_y: [-1.0, 1.0]
  limit_vel_yaw: [-1.5, 1.5]
  limit_body_height: [0.0, 0.0]
  limit_gait_phase: [0.0, 0.0]
  limit_gait_offset: [0.0, 0.0]
  limit_gait_bound: [0.0, 0.0]
  limit_gait_frequency: [0.0, 0.0]
  limit_gait_duration: [0.0, 0.0]
  limit_footswing_height: [0.0, 0.0]
  limit_body_pitch: [0.0, 0.0]
  limit_body_roll: [0.0, 0.0]
  limit_aux_reward_coef: [0.0, 0.0]
  limit_compliance: [0.0, 0.01]
  limit_stance_width: [0.0, 0.0]
  limit_stance_length: [0.0, 0.0]
  num_bins_vel_x: 10
  num_bins_vel_y: 10
  num_bins_vel_yaw: 10
  num_bins_body_height: 1
  num_bins_gait_frequency: 1
  num_bins_gait_phase: 1
  num_bins_gait_offset: 1
  num_bins_gait_bound: 1
  num_bins_gait_duration: 3
  num_bins_footswing_height: 1
  num_bins_body_pitch: 1
  num_bins_body_roll: 1
  num_bins_aux_reward_coef: 1
  num_bins_compliance: 1
  num_bins_stance_width: 1
  num_bins_stance_length: 1
  heading_range: [-3.14, 3.14]
  gait_phase_cmd_range: [0.0, 0.0]
  gait_offset_cmd_range: [0.0, 0.0]
  gait_bound_cmd_range: [0.0, 0.0]
  gait_frequency_cmd_range: [0.0, 0.0]
  gait_duration_cmd_range: [0.0, 0.0]
  footswing_height_range: [0.0, 0.0]
  body_pitch_range: [0.0, 0.0]
  body_roll_range: [0.0, 0.0]
  aux_reward_coef_range: [0.0, 0.0]
  stance_width_range: [0.0, 0.0]
  stance_length_range: [0.0, 0.0]
  exclusive_phase_offset: true
  binary_phases: false
  pacing_offset: false
  balance_gait_distribution: true
  gaitwise_curricula: true
  train_standing_still: true
  standing_still_prob: 0.05
  standing_still_explicit_flag: false
  heading: [-3.14, 3.14]
